// <auto-generated />
using System;
using DoAn_GiaiDoan1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DoAn_GiaiDoan1.Migrations
{
    [DbContext(typeof(QLQKDbContext))]
    [Migration("20260205121017_KhoiTaoCSDL")]
    partial class KhoiTaoCSDL
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DoAn_GiaiDoan1.Data.ChiTietHoaDon", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("HoaDonID")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.HasIndex("HoaDonID");

                    b.ToTable("ChiTietHoaDon");
                });

            modelBuilder.Entity("DoAn_GiaiDoan1.Data.ChiTietKhuyenMai", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("HoaDonID")
                        .HasColumnType("int");

                    b.Property<int>("KhuyenMaiID")
                        .HasColumnType("int");

                    b.Property<decimal>("SoTienGiam")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.HasIndex("HoaDonID");

                    b.HasIndex("KhuyenMaiID");

                    b.ToTable("ChiTietKhuyenMai");
                });

            modelBuilder.Entity("DoAn_GiaiDoan1.Data.DatPhong", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("KhachHangID")
                        .HasColumnType("int");

                    b.Property<int>("NhanVienID")
                        .HasColumnType("int");

                    b.Property<int>("PhongID")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGianBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianKetThuc")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("KhachHangID");

                    b.HasIndex("NhanVienID");

                    b.HasIndex("PhongID");

                    b.ToTable("DatPhong");
                });

            modelBuilder.Entity("DoAn_GiaiDoan1.Data.DichVu", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TenDV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("DichVu");
                });

            modelBuilder.Entity("DoAn_GiaiDoan1.Data.HoaDon", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("DatPhongID")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGianLap")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.HasIndex("DatPhongID");

                    b.ToTable("HoaDon");
                });

            modelBuilder.Entity("DoAn_GiaiDoan1.Data.KhachHang", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("DienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenKH")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("KhachHang");
                });

            modelBuilder.Entity("DoAn_GiaiDoan1.Data.KhuyenMai", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal>("PhanTramGiam")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TenKhuyenMai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("KhuyenMai");
                });

            modelBuilder.Entity("DoAn_GiaiDoan1.Data.LoaiPhong", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal>("GiaGio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SucChua")
                        .HasColumnType("int");

                    b.Property<string>("TenLoaiPhong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("LoaiPhong");
                });

            modelBuilder.Entity("DoAn_GiaiDoan1.Data.NhanVien", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("ChucVu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("NhanVien");
                });

            modelBuilder.Entity("DoAn_GiaiDoan1.Data.Phong", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LoaiPhongID")
                        .HasColumnType("int");

                    b.Property<string>("TenPhong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("LoaiPhongID");

                    b.ToTable("Phong");
                });

            modelBuilder.Entity("DoAn_GiaiDoan1.Data.SuDungDichVu", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("DatPhongID")
                        .HasColumnType("int");

                    b.Property<int>("DichVuID")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("DatPhongID");

                    b.HasIndex("DichVuID");

                    b.ToTable("SuDungDichVu");
                });

            modelBuilder.Entity("DoAn_GiaiDoan1.Data.TaiKhoan", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NhanVienID")
                        .HasColumnType("int");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("NhanVienID")
                        .IsUnique();

                    b.ToTable("TaiKhoan");
                });

            modelBuilder.Entity("DoAn_GiaiDoan1.Data.ThanhToan", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("HoaDonID")
                        .HasColumnType("int");

                    b.Property<string>("PhuongThuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ThoiGianThanhToan")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("HoaDonID");

                    b.ToTable("ThanhToan");
                });

            modelBuilder.Entity("DoAn_GiaiDoan1.Data.ChiTietHoaDon", b =>
                {
                    b.HasOne("DoAn_GiaiDoan1.Data.HoaDon", "HoaDon")
                        .WithMany("ChiTietHoaDon")
                        .HasForeignKey("HoaDonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("DoAn_GiaiDoan1.Data.ChiTietKhuyenMai", b =>
                {
                    b.HasOne("DoAn_GiaiDoan1.Data.HoaDon", "HoaDon")
                        .WithMany("ChiTietKhuyenMai")
                        .HasForeignKey("HoaDonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAn_GiaiDoan1.Data.KhuyenMai", "KhuyenMai")
                        .WithMany("ChiTietKhuyenMai")
                        .HasForeignKey("KhuyenMaiID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoaDon");

                    b.Navigation("KhuyenMai");
                });

            modelBuilder.Entity("DoAn_GiaiDoan1.Data.DatPhong", b =>
                {
                    b.HasOne("DoAn_GiaiDoan1.Data.KhachHang", "KhachHang")
                        .WithMany("DatPhong")
                        .HasForeignKey("KhachHangID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAn_GiaiDoan1.Data.NhanVien", "NhanVien")
                        .WithMany("DatPhong")
                        .HasForeignKey("NhanVienID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAn_GiaiDoan1.Data.Phong", "Phong")
                        .WithMany("DatPhong")
                        .HasForeignKey("PhongID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("NhanVien");

                    b.Navigation("Phong");
                });

            modelBuilder.Entity("DoAn_GiaiDoan1.Data.HoaDon", b =>
                {
                    b.HasOne("DoAn_GiaiDoan1.Data.DatPhong", "DatPhong")
                        .WithMany("HoaDon")
                        .HasForeignKey("DatPhongID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DatPhong");
                });

            modelBuilder.Entity("DoAn_GiaiDoan1.Data.Phong", b =>
                {
                    b.HasOne("DoAn_GiaiDoan1.Data.LoaiPhong", "LoaiPhong")
                        .WithMany("Phong")
                        .HasForeignKey("LoaiPhongID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiPhong");
                });

            modelBuilder.Entity("DoAn_GiaiDoan1.Data.SuDungDichVu", b =>
                {
                    b.HasOne("DoAn_GiaiDoan1.Data.DatPhong", "DatPhong")
                        .WithMany("SuDungDichVu")
                        .HasForeignKey("DatPhongID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAn_GiaiDoan1.Data.DichVu", "DichVu")
                        .WithMany("SuDungDichVu")
                        .HasForeignKey("DichVuID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DatPhong");

                    b.Navigation("DichVu");
                });

            modelBuilder.Entity("DoAn_GiaiDoan1.Data.TaiKhoan", b =>
                {
                    b.HasOne("DoAn_GiaiDoan1.Data.NhanVien", "NhanVien")
                        .WithOne("TaiKhoan")
                        .HasForeignKey("DoAn_GiaiDoan1.Data.TaiKhoan", "NhanVienID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("DoAn_GiaiDoan1.Data.ThanhToan", b =>
                {
                    b.HasOne("DoAn_GiaiDoan1.Data.HoaDon", "HoaDon")
                        .WithMany("ThanhToan")
                        .HasForeignKey("HoaDonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("DoAn_GiaiDoan1.Data.DatPhong", b =>
                {
                    b.Navigation("HoaDon");

                    b.Navigation("SuDungDichVu");
                });

            modelBuilder.Entity("DoAn_GiaiDoan1.Data.DichVu", b =>
                {
                    b.Navigation("SuDungDichVu");
                });

            modelBuilder.Entity("DoAn_GiaiDoan1.Data.HoaDon", b =>
                {
                    b.Navigation("ChiTietHoaDon");

                    b.Navigation("ChiTietKhuyenMai");

                    b.Navigation("ThanhToan");
                });

            modelBuilder.Entity("DoAn_GiaiDoan1.Data.KhachHang", b =>
                {
                    b.Navigation("DatPhong");
                });

            modelBuilder.Entity("DoAn_GiaiDoan1.Data.KhuyenMai", b =>
                {
                    b.Navigation("ChiTietKhuyenMai");
                });

            modelBuilder.Entity("DoAn_GiaiDoan1.Data.LoaiPhong", b =>
                {
                    b.Navigation("Phong");
                });

            modelBuilder.Entity("DoAn_GiaiDoan1.Data.NhanVien", b =>
                {
                    b.Navigation("DatPhong");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("DoAn_GiaiDoan1.Data.Phong", b =>
                {
                    b.Navigation("DatPhong");
                });
#pragma warning restore 612, 618
        }
    }
}
